# Generated by Django 6.0.3 on 2026-03-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_likes_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
