# Generated by Django 6.0.3 on 2026-03-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
